import { Link } from 'react-router-dom'

export default function Accessibility() {
  return (
    <div className="min-h-screen bg-[#0A0B12] text-white">
      <a href="#main-content" className="skip-link">Skip to main content</a>
      {/* Nav */}
      <nav aria-label="Page navigation" className="flex items-center justify-between px-6 md:px-12 h-16 border-b border-white/[0.06] sticky top-0 z-50 backdrop-blur-md bg-[#0A0B12]/80">
        <Link to="/" aria-label="ShopCommand home" className="flex items-center gap-2 hover:opacity-70 transition-opacity">
          <svg width="26" height="26" viewBox="0 0 64 64" role="img" aria-hidden="true">
            <polygon points="32.00,4.00 56.25,18.00 56.25,46.00 32.00,60.00 7.75,46.00 7.75,18.00" fill="#F97316" />
            <polygon points="32.00,16.82 45.58,24.66 45.58,40.34 32.00,48.18 18.42,40.34 18.42,24.66" fill="#0A0B12" />
          </svg>
          <span style={{ letterSpacing: '-0.02em' }} className="text-sm font-semibold">
            Shop<span className="text-orange-500">Command</span>
          </span>
        </Link>
        <Link to="/login" className="px-4 py-1.5 rounded-lg text-sm font-semibold bg-orange-500 hover:bg-orange-400 text-white transition-colors">
          Log in
        </Link>
      </nav>

      <main id="main-content">
      {/* Content */}
      <div className="max-w-3xl mx-auto px-6 py-16">
        <div className="mb-10">
          <h1 style={{ letterSpacing: '-0.02em' }} className="text-3xl font-bold text-white mb-2">Accessibility Statement</h1>
          <p className="text-white/40 text-sm">Last updated: May 31, 2026</p>
        </div>

        <div className="prose prose-invert prose-sm max-w-none space-y-8 text-white/70 leading-relaxed">

          {/* Commitment */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">Our Commitment</h2>
            <p>
              ShopCommand is committed to ensuring digital accessibility for people with disabilities. We are continually improving the user experience for everyone and applying the relevant accessibility standards to ensure we provide equal access to all users.
            </p>
          </section>

          {/* Standards */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">Conformance Standard</h2>
            <p>
              We aim to conform to the Web Content Accessibility Guidelines (WCAG) 2.1 at Level AA. These guidelines explain how to make web content more accessible for people with disabilities and more user-friendly for everyone.
            </p>
          </section>

          {/* Measures */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">Accessibility Measures</h2>
            <p>ShopCommand takes the following measures to ensure accessibility:</p>
            <ul className="list-disc pl-5 space-y-2 mt-3">
              <li>Semantic HTML elements for proper document structure and screen reader navigation.</li>
              <li>Sufficient color contrast ratios between text and background colors.</li>
              <li>Keyboard navigable interfaces so all features can be used without a mouse.</li>
              <li>ARIA labels and roles where native HTML semantics are insufficient.</li>
              <li>Visible focus indicators for interactive elements.</li>
              <li>Responsive design that works across devices and zoom levels up to 200%.</li>
              <li>Form inputs with associated labels and clear error messages.</li>
              <li>No content that flashes more than three times per second.</li>
            </ul>
          </section>

          {/* Known Limitations */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">Known Limitations</h2>
            <p>
              While we strive for full WCAG 2.1 AA compliance, some areas of the application may not yet be fully accessible. We are actively working to identify and resolve these issues. Known limitations include:
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-3">
              <li>Some data-heavy tables and charts in the dashboard may have limited screen reader support. We are working on accessible alternatives.</li>
              <li>Older PDF documents generated by the system may not be fully accessible. New documents are generated with accessibility in mind.</li>
            </ul>
          </section>

          {/* Assistive Technologies */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">Compatibility</h2>
            <p>ShopCommand is designed to be compatible with the following assistive technologies:</p>
            <ul className="list-disc pl-5 space-y-2 mt-3">
              <li>Screen readers (NVDA, JAWS, VoiceOver, TalkBack)</li>
              <li>Screen magnification software</li>
              <li>Speech recognition software</li>
              <li>Keyboard-only navigation</li>
            </ul>
            <p className="mt-3">
              ShopCommand is designed to work with current versions of Chrome, Firefox, Safari, and Edge.
            </p>
          </section>

          {/* Feedback */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">Feedback and Contact</h2>
            <p>
              We welcome your feedback on the accessibility of ShopCommand. If you encounter accessibility barriers or have suggestions for improvement, please contact us:
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-3">
              <li>Email: <a href="mailto:accessibility@shopcommand.com" className="text-orange-400 hover:underline">accessibility@shopcommand.com</a></li>
            </ul>
            <p className="mt-3">
              We try to respond to accessibility feedback within 3 business days and to resolve issues within 10 business days.
            </p>
          </section>

          {/* Enforcement */}
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">Enforcement</h2>
            <p>
              If you are not satisfied with our response to your accessibility concern, you may file a complaint with the U.S. Department of Justice, Civil Rights Division, or your local equal rights agency. We are committed to resolving any accessibility issues and appreciate you bringing them to our attention.
            </p>
          </section>

        </div>
      </div>

      {/* Footer */}
      <footer aria-label="Page footer" className="border-t border-white/[0.06] px-6 py-8 flex flex-col md:flex-row items-center justify-between gap-4 max-w-3xl mx-auto">
        <p className="text-slate-500 text-xs">© 2026 ShopCommand. All rights reserved.</p>
        <div className="flex gap-4">
          <Link to="/terms" className="text-white/60 hover:text-white/80 text-xs transition-colors">Terms of Service</Link>
          <Link to="/privacy" className="text-white/60 hover:text-white/80 text-xs transition-colors">Privacy Policy</Link>
          <Link to="/dpa" className="text-white/60 hover:text-white/80 text-xs transition-colors">DPA</Link>
          <Link to="/cookies" className="text-white/60 hover:text-white/80 text-xs transition-colors">Cookies</Link>
        </div>
      </footer>
      </main>
    </div>
  )
}
